# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: poetry install --no-dev --no-root
      - name: Test with Unittest
        run: poetry run python -m unittest discover -v -s ./tests

  integrationtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'bats-core/bats-core'
          path: 'bats'
      - uses: actions/checkout@v2
        with:
          repository: 'bats-core/bats-support'
          path: 'test_helper/bats-support'
      - uses: actions/checkout@v2
        with:
          repository: 'bats-core/bats-assert'
          path: 'test_helper/bats-assert'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: poetry install --no-dev
      - name: Run Tests
        run: ./bats/bin/bats -rT ./tests
        env:
          BATS_LIB_PATH: '${GITHUB_WORKSPACE}/test_helper'
